// <auto-generated />
using System;
using Halloween.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Halloween.Migrations
{
    [DbContext(typeof(HalloweenContext))]
    [Migration("20230925192700_AjoutSorcierePotionSeed")]
    partial class AjoutSorcierePotionSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Halloween.Models.Potion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sorciere_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sorciere_Id");

                    b.ToTable("Potions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(1811, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Elixir cérébral de Barrufio",
                            Sorciere_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(1815, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Philtre d'apathie",
                            Sorciere_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(1817, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion de perception",
                            Sorciere_Id = 3
                        },
                        new
                        {
                            Id = 4,
                            DateCreation = new DateTime(1634, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion Exstimulo",
                            Sorciere_Id = 4
                        },
                        new
                        {
                            Id = 5,
                            DateCreation = new DateTime(1642, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion Exstimulo renforcée",
                            Sorciere_Id = 4
                        },
                        new
                        {
                            Id = 6,
                            DateCreation = new DateTime(1732, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion Exstimulo puissante",
                            Sorciere_Id = 5
                        },
                        new
                        {
                            Id = 7,
                            DateCreation = new DateTime(1721, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion de Soin",
                            Sorciere_Id = 6
                        },
                        new
                        {
                            Id = 8,
                            DateCreation = new DateTime(1787, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion scintillante",
                            Sorciere_Id = 2
                        },
                        new
                        {
                            Id = 9,
                            DateCreation = new DateTime(1634, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion d'Aiguise-Méninges",
                            Sorciere_Id = 7
                        },
                        new
                        {
                            Id = 10,
                            DateCreation = new DateTime(1819, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Breuvage abondant",
                            Sorciere_Id = 3
                        },
                        new
                        {
                            Id = 11,
                            DateCreation = new DateTime(1651, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion de Mémoire",
                            Sorciere_Id = 8
                        },
                        new
                        {
                            Id = 12,
                            DateCreation = new DateTime(1842, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion revigorante forte",
                            Sorciere_Id = 2
                        },
                        new
                        {
                            Id = 13,
                            DateCreation = new DateTime(1652, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion de l'Œil Vif",
                            Sorciere_Id = 8
                        },
                        new
                        {
                            Id = 14,
                            DateCreation = new DateTime(1789, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Potion d'invisibilité",
                            Sorciere_Id = 2
                        });
                });

            modelBuilder.Entity("Halloween.Models.Sorciere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sorcieres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Maléfique",
                            Origine = "Belle au bois dormant"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Belagile",
                            Origine = "Basque"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Morgane",
                            Origine = "Roi Arthur"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Médée",
                            Origine = "Grèce"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Taoueille",
                            Origine = "Acadie"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Andor",
                            Origine = "Acadie"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Merlin",
                            Origine = "Roi Arthur"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Mariecomo",
                            Origine = "Acadie"
                        });
                });

            modelBuilder.Entity("Halloween.Models.Potion", b =>
                {
                    b.HasOne("Halloween.Models.Sorciere", "Creatrice")
                        .WithMany("Potions")
                        .HasForeignKey("Sorciere_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creatrice");
                });

            modelBuilder.Entity("Halloween.Models.Sorciere", b =>
                {
                    b.Navigation("Potions");
                });
#pragma warning restore 612, 618
        }
    }
}
